import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const shouldShowAnalytics = () => {
  const d = new Date().getTime();
  return d % 2 === 0;
};

export default function RootLayout({
  children,
  analytics,
  team
}: Readonly<{
  children: React.ReactNode;
  analytics: React.ReactNode;
  team: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        {shouldShowAnalytics() ? analytics : team}
      </body>

    </html>
  );
}
