import { MenuLink } from "./types";

export const Destinations:MenuLink[] = [
    {label: "all destinations", link: "/"},
    {label: "abbotsford", link: "/"},
    {label: "calgary", link: "/"},
    {label: "cancun", link: "/"},
    {label: "charlottetown", link: "/"},
    {label: "deer lake", link: "/"},
    {label: "edmonton", link: "/"},
    {label: "fort lauderdale", link: "/"},
    {label: "guadalajara", link: "/"},
    {label: "halifax", link: "/"},
    {label: "kelowna", link: "/"},
    {label: "kingston", link: "/"},
    {label: "kitchener-waterloo", link: "/"},
    {label: "las vegas", link: "/"},
    {label: "london", link: "/"},
    {label: "los angeles", link: "/"},
    {label: "los cabos", link: "/"},
    {label: "montreal", link: "/"},
    {label: "nashville", link: "/"},
    {label: "new york", link: "/"},
    {label: "orlando", link: "/"},
    {label: "ottawa", link: "/"},
    {label: "palm springs", link: "/"},
    {label: "phoenix", link: "/"},
    {label: "puerto vallarta", link: "/"},
    {label: "punta cana", link: "/"},
    {label: "quebec city", link: "/"},
    {label: "saint john", link: "/"},
    {label: "st. john's", link: "/"},
    {label: "san francisco", link: "/"},
    {label: "saskatoon", link: "/"},
    {label: "thunder bay", link: "/"},
    {label: "toronto", link: "/"},
    {label: "vancouver", link: "/"},
    {label: "victoria", link: "/"},
    {label: "windsor", link: "/"},
    {label: "winnipeg", link: "/"}
];

